<a href="https://colab.research.google.com/github/srinisosale/python-pgpaiml/blob/main/PracticeExercisesWeek3_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
myString = "python"
myString

'python'

In [ ]:
myList = ['Data Science','Machine Learning','Artificial Intelligence','python']
myList

['Data Science', 'Machine Learning', 'Artificial Intelligence', 'python']

In [ ]:
if myString in myList:
  print(myString + ' Tutorial')

python Tutorial


In [ ]:
myLanguages = ['Java', 'Python', 'Perl,','Ruby','c#']
if 'Java' in myLanguages:
  print('right')

right


In [ ]:
x=500
print(x)
if not x == 500:
  print('The value of different from 500')
else:
    print('The value of is equal to 500')

500
The value of is equal to 500


In [ ]:
string1=str(input("enter your userid"))
string2=str(input("enter your password"))
if(string1=="greatLearning" and string2=="simpleLearning123"):
  print("Successfully loggedin!!")
else:
    print("Please check your userid or password")
    


enter your useridgreatLearning
enter your passwordsimpleLearning123
Successfully loggedin!!


In [ ]:
num=1
if(num==0):
  print("Number is Zero")
elif(num>5):
  print("Number is greater than 50")
else:
  print("Number is smaller than 50")


Number is smaller than 50


In [ ]:
num=float(input("Enter a number: "))
if(num >= 0):
  if(num==0):
    print("Zero")
  else:
      print("Positive Number")
else:
  print("Negative Number")

Enter a number: -1
Negative Number


In [ ]:
if2>5:
  print("True")
else: 2<5
  print("False")

Program to find list of numbers

In [ ]:
numbers=[66,545,223,438,224,122,125,214,111,344]
#variable to store sum
sum=0
#iterate over the list
for val in numbers:
  sum=sum+val
#output: The sum is
print("The sum is", sum)

The sum is 2412


While loop

Calculate the sum of integers

In [ ]:
a=0
b=0
while(a<10):
  b=b+a
  a=a+1
else:
  print("The sum of first 9 integers: ",b)



The sum of first 9 integers:  45


In [ ]:
numb=[1, 2, 3, 4]
numb_new=[]
for i in numb:
    if i>=3:
        numb_new.append(i)
    else:
        numb_new.append(0)
print(numb_new)

[0, 0, 3, 4]


In [ ]:
for i in range(5):
  a=int(input())
  if a<0:
    print('met a negative number',a)
    break
else:
  print('no negative numbers met')


87
67
44
76
98
no negative numbers met


In [ ]:
l=[0, 1, 2, 3, 4]
for i in l:
    if i%2==0:
        continue
    break 

In [ ]:
i=0
while i<9999999:
    if i==6:
        print(6)
        break
    else:
        i = i+1 

6


In [ ]:
num=1%2
num

1

In [ ]:
def function(**kwargs):
  for a,b in kwargs.items():
    print(a,"==",b)

a=function(A="First Letter", B="Second Letter", C="Third Letter")

A == First Letter
B == Second Letter
C == Third Letter


In [ ]:
marks = [ 10, 23, 34, 45, 33, 10, 43, 23, 27, 34, 37, 44, 42, 43 ]
print(list(map(lambda x,y=100:x*y/45,marks)))

[22.22222222222222, 51.111111111111114, 75.55555555555556, 100.0, 73.33333333333333, 22.22222222222222, 95.55555555555556, 51.111111111111114, 60.0, 75.55555555555556, 82.22222222222223, 97.77777777777777, 93.33333333333333, 95.55555555555556]


In [ ]:
def twice():
  a=int(input('Enter a number'))
  print(a*2)

twice()

Enter a number3
6


In [ ]:
def add():
  print(1+2)

In [ ]:
def average(x):
  count = 0
  total = 0
  for i in x:
    count += 1
    total += i
  avg=total/count
  return avg

x=(20,30)
average(x)


25.0

    ITP Project using the notes
    

In [ ]:
def main():
  overallBudget = 5000
  selection = 0
  while selection != '4':
    print('1= Add on Expense')
    print('2= subtract on Expense')
    print('3= Add on Revenue')
    print('4= Subtract Revenue')
    print('5= Balance enquiry')
    print('6 = Exit')

    selection = int(input('Please enter a choice'))
    if selection == 1:
      overallBudget = additionOfExpense(overallBudget)
    elif selection == 2:
      overallBudget = subtractionOfExpense(overallBudget)
    elif selection == 3:
      overallBudget = additionOfRevenue(overallBudget)
    elif selection == 4:
      overallBudget = subtractionOfRevenue(overallBudget)
    elif selection == 5:
      print('Your Balance is: ',overallBudget)
    elif selection == 6:
      print("Thank You")
      break
    else:
      print('Wrong Entry')

def additionOfExpense(overallBudget):
  billing = int(input('Enter the amount of Expense: '))
  billFreq = int(input('Enter the frequency of Expense per month: '))
  totalBill = billing*billFreq
  overallBudget=overallBudget - totalBill
  checkOnBudget(overallBudget)
  return overallBudget

def subtractionOfExpense(overallBudget):
  lessBill = int(input('Enter the amount to be subtracted: '))
  lessBillFreq = int(input('Enter the frequency of amount subtraction: '))
  totalLess = lessBill * lessBillFreq
  if totalLess <= overallBudget:
    overallBudget = overallBudget + totalLess
    checkOnBudget(overallBudget)
  else:
    print('Please check the amount entered..')
    return overallBudget
  return overallBudget

def additionOfRevenue(overallBudget):
  income = int(input('Enter the amount of income: '))
  checkOnBudget(overallBudget)
  overallBudget = overallBudget + income

  return overallBudget

def subtractionOfRevenue(overallBudget):
  lossIncome = int(input('Enter the loss: '))
  overallBudget = overallBudget - lossIncome
  checkOnBudget(overallBudget)

  return overallBudget

def checkOnBudget(overallBudget):
  if (overallBudget >= 0):
    print('Overall budget remaining is : ', overallBudget)
  else:
    print('You have exceeded monthly budget')
    print('Current Balance is: ',overallBudget)

    

main()

1= Add on Expense
2= subtract on Expense
3= Add on Revenue
4= Subtract Revenue
5= Balance enquiry
6 = Exit
Your Balance is:  5000
1= Add on Expense
2= subtract on Expense
3= Add on Revenue
4= Subtract Revenue
5= Balance enquiry
6 = Exit
Overall budget remaining is :  7400
1= Add on Expense
2= subtract on Expense
3= Add on Revenue
4= Subtract Revenue
5= Balance enquiry
6 = Exit
Your Balance is:  7400
1= Add on Expense
2= subtract on Expense
3= Add on Revenue
4= Subtract Revenue
5= Balance enquiry
6 = Exit
Overall budget remaining is :  5000
1= Add on Expense
2= subtract on Expense
3= Add on Revenue
4= Subtract Revenue
5= Balance enquiry
6 = Exit
Overall budget remaining is :  2600
1= Add on Expense
2= subtract on Expense
3= Add on Revenue
4= Subtract Revenue
5= Balance enquiry
6 = Exit
Wrong Entry
1= Add on Expense
2= subtract on Expense
3= Add on Revenue
4= Subtract Revenue
5= Balance enquiry
6 = Exit
Overall budget remaining is :  2599
1= Add on Expense
2= subtract on Expense
3= Add o

In [ ]:
def cube(n):
    if n==10:
        return 1
    print(n**3)
    cube(n+1)
cube(0)

0
1
8
27
64
125
216
343
512
729


In [ ]:
def cube(n):
    return n**3
for i in range(0,10):
    c=cube(i)
    print(c)

0
1
8
27
64
125
216
343
512
729


In [ ]:
def search(data_structure, ele):
  index=0
  while data_structure[index]!=ele:
    if index==len(data_structure)-1:
      return "Element not available"
    else: 
      index+=1
  return index

In [ ]:
l=[1, 2, 4]
search(l,6)

'Element not available'

In [ ]:
counts_of_vowels = 0
def vowels(str):
    for i in str:
        if i=="a" or i=="e" or i=="i" or i=="o" or i=="u":
            count_of_vowels+=1
    return count_of_vowels

In [ ]:
vowels("and")

UnboundLocalError: ignored

In [ ]:
def ranges(a,b):
    rangeList=list()
    if b > a:
        while a<=b:
            rangeList.append(a)
            a += 1
    else:
        while b<=a:
            rangeList.append(a)
            a -= 1
    return(rangeList)

In [ ]:
ranges(3,6)

[3, 4, 5, 6]

In [ ]:
inp1=int(input('Enter First Number: '))
inp2=int(input('Enter Second Number: '))
primeList=list()
for i in range(inp1,inp2):
    resp=prime(i)
    if resp=='prime':
        primeList.append(i)
print(primeList)

Enter First Number: 2
Enter Second Number: 50


NameError: ignored

In [ ]:

num1=1
num2=num1+1.5
num3=int(num2)
print(num3)

2


In [ ]:
numbs=("GreatLearning")
a=numbs[2:5]
print(a)


eat


In [ ]:
l=['T', 'F']
for i in l:
     for j in l:
          print(i+j)

TT
TF
FT
FF


In [ ]:
diction={1:'srini',2:'bhaskar',3:'shwe',3:'shwe'}
print(diction)

{1: 'srini', 2: 'bhaskar', 3: 'shwe'}


In [ ]:
numb_list=[1, 3, 2, 8, 0, 9]
numb_tuple=(2, 4, 7, 1)
numb_dictionary={'first': 1, 'second': 2, 'third':3}
numb_set={numb_list[0], numb_tuple[-1], numb_dictionary[‘first’]}
print(numb_set)

SyntaxError: ignored

In [ ]:
numb_list=[1, 3, 2, 8, 0, 9]
numb_tuple=(2, 4, 7, 1)
print(numb_list[0],numb_tuple[-1])

1 1


In [ ]:
numb_dictionary={'first': 1, 'second': 2, 'third':3}
print(numb_dictionary['first'])

1


In [ ]:
numb_tuple=(2,4,7,1)
print(numb_tuple[-1])

1


In [ ]:
numb_set={numb_list[0],numb_tuple[-1],numb_dictionary['first']}
print(numb_set)

NameError: ignored

In [ ]:
i=0
while i<5:
     print(i)
     i+=1

0
1
2
3
4


In [ ]:
x=”3.0”
if type(x)==int:
     print(‘int’)
elif type(x)==float:
     print(‘float’)
else:
     print(‘string’)

SyntaxError: ignored

In [ ]:
x="3.0"
if type(x)==int:
     print(‘ineger’)
elif type(x)==float:
     print(‘floate’)
else:
     print(‘string’)

SyntaxError: ignored

In [ ]:
var1=2
var2=2



In [ ]:
id(2),id(var1), id(var2)


(9793120, 9793120, 9793120)

In [ ]:
type(2.0)

float

In [ ]:
lst1 = [1,2,4,5] #list
dct1 = {'one': 1, 'two':2, 'three':3} #dictionary 
tup1 = (1,2,3,4,5) #tuple
set1 = {1,2,3,4} # set

In [ ]:
lst1[2]=3
print(lst1)

[1, 2, 3, 5]


In [ ]:
dct1['two']=3
print(dct1)

{'one': 1, 'two': 3, 'three': 3}


In [ ]:
data = [[1,2],[3,4]] #a nested list (a list containing 2 lists) 
print(data)
df = pd.DataFrame([[1,2],[3,4]], columns=['Col1','Col2'])
df

[[1, 2], [3, 4]]


NameError: ignored

In [ ]:
ans1=[1.2,3.4,5.6]
print(ans1)
type(ans1)

[1.2, 3.4, 5.6]


list

In [2]:
import numpy as np
import pandas as pd

In [ ]:
randarr = np.random.rand(10)

In [ ]:
arrStrList = ['one','two','three']
arrNumList = [1,3,5,4]
npArrStr = np.array(arrStrList)
npArrNum = np.array(arrNumList)
print(type(arrStrList),arrStrList)
print(type(arrNumList),arrNumList)
print(type(npArrStr),npArrStr)
print(type(npArrNum),npArrNum)


<class 'list'> ['one', 'two', 'three']
<class 'list'> [1, 3, 5, 4]
<class 'numpy.ndarray'> ['one' 'two' 'three']
<class 'numpy.ndarray'> [1 3 5 4]


In [ ]:
rand_arr= np.random.rand(10) 
print(rand_arr)

[0.12188867 0.65148642 0.71143908 0.21390557 0.91753952 0.68625873
 0.80664233 0.93595127 0.06628703 0.90443545]


In [ ]:
print('rand_array less than zero: ', rand_arr[rand_arr<0])

rand_array less than zero:  []


In [ ]:
rand_mtrx=np.random.randn(5,5)
print(rand_mtrx)

[[-0.5130038   0.07806852 -0.31179828  0.13697833  0.39418015]
 [ 0.44063648  0.95598392  0.43548825  0.18165858  1.47230253]
 [-0.76151295  1.09571373 -0.26075694  0.67017574 -0.55408349]
 [-1.31341187 -0.53792898 -0.14083725 -1.11835619 -1.23666448]
 [-2.01055603 -0.27230748 -0.29008018  1.34071008  1.73273745]]


In [ ]:
rand_mtrx[1]

array([0.44063648, 0.95598392, 0.43548825, 0.18165858, 1.47230253])

In [ ]:
rand_mtrx[4,3]

1.340710079505176

In [ ]:
test_array = [10, 11.5, 12, 13.5, 14,15]
test_array[2:3]
arr = np.array([1,2,3,4,5,6,7])
arr[2:5]
mat = np.array([[1,2,3,4,5], [6,7,8,9,10]])
mat[1,2]

8

In [ ]:
rand_mtrx = np.random.randn(5,5)
print(rand_mtrx)
snglrand = rand_mtrx[1]
print(snglrand)

[[-1.40563505 -0.45244469 -0.10234341  0.74495601  0.68813571]
 [ 0.5535273  -1.39097714 -0.46689228 -0.50910953 -0.89043751]
 [-1.94641863  0.54057263 -0.05663837  0.20827758 -1.41068163]
 [-1.29855676 -1.73860062 -0.18243108 -0.33206654 -1.67263259]
 [-1.44747743  0.94525719 -0.16462471  0.29856162  1.53283923]]
[ 0.5535273  -1.39097714 -0.46689228 -0.50910953 -0.89043751]


In [ ]:
snglrand = np.random.randn(10)
print(snglrand)

[ 0.82477065  1.95314402 -2.07606428 -0.70106778 -0.65492674  1.20262778
  0.4508962  -1.43104927 -0.14569104  0.19873531]


In [ ]:
snglrand[3:5]=5
print(snglrand)

[ 0.82477065  1.95314402 -2.07606428  5.          5.          1.20262778
  0.4508962  -1.43104927 -0.14569104  0.19873531]


In [ ]:
test_array = np.array([100, 1105, 172, 135, 147,153])
test_array[3:]=500
test_array

array([ 100, 1105,  172,  500,  500,  500])

In [ ]:
test_mat_1 = np.array([[1,2],[3,4],[5,6]])
test_mat_2 = test_mat_1
test_mat_2[1,0] = 2
test_mat_1[2,0] = 4
print(test_mat_1)

[[1 2]
 [2 4]
 [4 6]]


In [ ]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
randint_matrix1=np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix1)
print('')
randint_matrix2=np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)


[[8 3 7 8 4]
 [9 7 1 9 3]]

[[11 18 16 12 11]
 [10 17 19 10 13]]


In [ ]:
np.save('/content/drive/MyDrive/Colab Notebooks/saved_file_name', randint_matrix1)

In [ ]:
loaded_arr=np.load('/content/drive/MyDrive/Colab Notebooks/saved_file_name.npy')
print(loaded_arr)

[[6 2 7 4 3]
 [7 2 7 5 8]]


In [ ]:
np.savetxt('/content/drive/MyDrive/Colab Notebooks/saved_file_name.txt',randint_matrix1,delimiter=',')
rand_matx_txt=np.loadtxt('/content/drive/MyDrive/Colab Notebooks/saved_file_name.txt',delimiter=',')
print(rand_matx_txt)

[[8. 3. 7. 8. 4.]
 [9. 7. 1. 9. 3.]]


In [ ]:
#Create list of med prices
med_price_list=[55,25,75,48,90]
#Convert med price list into an array
med_price_arr=np.array(med_price_list)
#Convert list and array to pandas series object
series_list= pd.Series(med_price_list)
series_array=pd.Series(med_price_arr)
print(series_list)
print(series_array)

0    55
1    25
2    75
3    48
4    90
dtype: int64
0    55
1    25
2    75
3    48
4    90
dtype: int64


In [ ]:
#changing the index of series
med_price_index_lbld=pd.Series(med_price_list, index=['Omeprozole','Azithromycin','Metformin','Ibuprofin','Cetrizine'])
print(med_price_index_lbld)

Omeprozole      55
Azithromycin    25
Metformin       75
Ibuprofin       48
Cetrizine       90
dtype: int64


In [ ]:
#Add $2.50 to the Medicine Price List
med_price_index_lbld_upd=med_price_index_lbld + 2.5
print(med_price_index_lbld_upd)

Omeprozole      57.5
Azithromycin    27.5
Metformin       77.5
Ibuprofin       50.5
Cetrizine       92.5
dtype: float64


In [ ]:
new_price_lst=[77,45.5,100,50,80]
new_price_lbld=pd.Series(new_price_lst, index=['Omeprozole','Azithromycin','Metformin','Ibuprofin','Cetrizine'])
print(new_price_lbld)

Omeprozole       77.0
Azithromycin     45.5
Metformin       100.0
Ibuprofin        50.0
Cetrizine        80.0
dtype: float64


In [ ]:
print('Price differnce between Old and New Med prices')
print(new_price_lbld - med_price_index_lbld_upd)

Price differnce between Old and New Med prices
Omeprozole      19.5
Azithromycin    18.0
Metformin       22.5
Ibuprofin       -0.5
Cetrizine      -12.5
dtype: float64


In [ ]:
#Create a List of students
student = ['Mary','Pierce','Toby','Susan','Vishal']
#Create a dataframe with Student List and Column Name
df1=pd.DataFrame(student,columns=['Student'])
df1

Student
0    Mary
1  Pierce
2    Toby
3   Susan
4  Vishal

In [ ]:
#Create a List of Grades
grades=['B-','A+','A-','B','C']

#Create a dataframe with a Dictionary
df2=pd.DataFrame({'Student':student,'Grade':grades})
df2

Student Grade
0    Mary    B-
1  Pierce    A+
2    Toby    A-
3   Susan     B
4  Vishal     C

In [9]:
#Create a pandas series for Year
year=pd.Series(['2015','2016','2017','2018','2019','2020','2021','2022'])
energy_consumption=pd.Series(['2152','2196','2210','2224','2232','2238','2241','2241'])
df3=pd.DataFrame({'Year':year,'energy_cons':energy_consumption})
df3

Year energy_cons
0  2015        2152
1  2016        2196
2  2017        2210
3  2018        2224
4  2019        2232
5  2020        2238
6  2021        2241
7  2022        2241

In [11]:
year.v

pandas.core.series.Series

In [10]:
type(df3)

pandas.core.frame.DataFrame

In [ ]:
from IPython.lib.security import random
#Can create a pandas series using numpy matrix
df4=pd.DataFrame(np.random.randn(5,2),columns=['Trial 1','Trial 2'])
df4

Trial 1   Trial 2
0 -0.495627 -0.924501
1  0.541681  0.951751
2 -0.062749  0.061506
3 -0.041002 -1.516697
4  0.305391  1.502458

In [ ]:
from IPython.core.compilerop import operator
#Create lists for telephone operators and their revenuss
operator=['AT&T','T-Mobile','Verizon']
revenue=[171.3, 165.4, 181.3]
#Create Pandas Series out of the above
telecoms=pd.Series(revenue, index=operator)
telecoms

AT&T        171.3
T-Mobile    165.4
Verizon     181.3
dtype: float64

In [ ]:

telecoms['Verizon']

181.3

In [7]:
import numpy as np
import pandas as pd

In [ ]:
#Create Dictionary of lists for customer,location,gender,type,quantity,total bill
store_data=pd.DataFrame({'Customer Id': ['C10001', 'C10002','C10003','C10004','C10005'],
                         'location': ['New York','Boston','Philadelphia','DC','Atlanta'],
                         'Gender': ['M','F','F','M','F'],
                         'Type': ['Food Beverages','Electronics','Cosmetics','Clothing','Hardware'],
                         'Quantity':[45,67,75,88,34],
                         'Bill': [1565,2256,5567,7559,4778]})
store_data

Customer Id      location Gender            Type  Quantity  Bill
0      C10001      New York      M  Food Beverages        45  1565
1      C10002        Boston      F     Electronics        67  2256
2      C10003  Philadelphia      F       Cosmetics        75  5567
3      C10004            DC      M        Clothing        88  7559
4      C10005       Atlanta      F        Hardware        34  4778

In [ ]:
store_data[1::2]

Customer Id location Gender         Type  Quantity  Bill
1      C10002   Boston      F  Electronics        67  2256
3      C10004       DC      M     Clothing        88  7559

In [ ]:
#accessing individual rows 0,1
store_data[:2]

Customer Id  location Gender            Type  Quantity  Bill
0      C10001  New York      M  Food Beverages        45  1565
1      C10002    Boston      F     Electronics        67  2256

In [ ]:
#accessing data by column = Results in a series
store_data['Type']

0    Food Beverages
1       Electronics
2         Cosmetics
3          Clothing
4          Hardware
Name: Type, dtype: object

In [ ]:
#access data from 0 to end, step by 2
store_data[::2]

Customer Id      location Gender            Type  Quantity  Bill
0      C10001      New York      M  Food Beverages        45  1565
2      C10003  Philadelphia      F       Cosmetics        75  5567
4      C10005       Atlanta      F        Hardware        34  4778

In [ ]:
#access data from bottom to top(reverse order), hence -1
store_data[::-1]

Customer Id      location Gender            Type  Quantity  Bill
4      C10005       Atlanta      F        Hardware        34  4778
3      C10004            DC      M        Clothing        88  7559
2      C10003  Philadelphia      F       Cosmetics        75  5567
1      C10002        Boston      F     Electronics        67  2256
0      C10001      New York      M  Food Beverages        45  1565

In [ ]:
store_data.loc[1]


Customer Id         C10002
location            Boston
Gender                   F
Type           Electronics
Quantity                67
Bill                  2256
Name: 1, dtype: object

In [ ]:
store_data.iloc[[1,3],[1,3]]

location         Type
1   Boston  Electronics
3       DC     Clothing

In [ ]:
store_data

Customer Id      location Gender            Type  Quantity  Bill
0      C10001      New York      M  Food Beverages        45  1565
1      C10002        Boston      F     Electronics        67  2256
2      C10003  Philadelphia      F       Cosmetics        75  5567
3      C10004            DC      M        Clothing        88  7559
4      C10005       Atlanta      F        Hardware        34  4778

In [ ]:
#adding a new column to store_data data frame
store_data['Rating']=['5','6','7','6','6']
store_data

Customer Id      location Gender            Type  Quantity  Bill Rating
0      C10001      New York      M  Food Beverages        45  1565      5
1      C10002        Boston      F     Electronics        67  2256      6
2      C10003  Philadelphia      F       Cosmetics        75  5567      7
3      C10004            DC      M        Clothing        88  7559      6
4      C10005       Atlanta      F        Hardware        34  4778      6

In [ ]:
store_data['Bill']==7559

0    False
1    False
2    False
3     True
4    False
Name: Bill, dtype: bool

In [ ]:
store_data[store_data['Bill']>1000]

Customer Id      location Gender            Type  Quantity  Bill
0      C10001      New York      M  Food Beverages        45  1565
1      C10002        Boston      F     Electronics        67  2256
2      C10003  Philadelphia      F       Cosmetics        75  5567
3      C10004            DC      M        Clothing        88  7559
4      C10005       Atlanta      F        Hardware        34  4778

In [ ]:
# create a new dataframe with one less row after drop the row in the original dataframe
store_data_new= store_data.drop(1,axis=0)
store_data_new

Customer Id      location Gender            Type  Quantity  Bill
0      C10001      New York      M  Food Beverages        45  1565
2      C10003  Philadelphia      F       Cosmetics        75  5567
3      C10004            DC      M        Clothing        88  7559
4      C10005       Atlanta      F        Hardware        34  4778

In [8]:
#reset the index on the store_data_new dataframe
store_data_new.reset_index()
store_data_new

NameError: ignored

In [1]:
#mount the google drive first
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [5]:
#set the path for the location of the csv and read
path="/content/drive/MyDrive/Colab Notebooks/StockData.csv"
data=pd.read_csv(path)


FileNotFoundError: ignored

In [6]:
#Display using head method the first five records
data.head()

stock        date    price
0  AAPL  08-02-2013  67.8542
1  AAPL  11-02-2013  68.5614
2  AAPL  12-02-2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556

In [8]:
#Save the dataframe data into a local drive or google drive
data.to_csv('/content/drive/MyDrive/Colab Notebooks/Saved_StockData.csv',index=False)

In [12]:
#Read the saved data from the drive
path='/content/drive/MyDrive/Colab Notebooks/Saved_StockData.csv'
dataFromSaveddriveCsv=pd.read_csv(path)

In [15]:
#Read the saved data for the first five
dataFromSaveddriveCsv.head()

stock        date    price
0  AAPL  08-02-2013  67.8542
1  AAPL  11-02-2013  68.5614
2  AAPL  12-02-2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556

In [7]:
#set the path for the location of the excel and read
pathExcel="/content/drive/MyDrive/Colab Notebooks/StockData.xlsx"
dataExcel=pd.read_excel(pathExcel)

In [9]:
dataExcel.to_excel('/content/drive/MyDrive/Colab Notebooks/Saved_StockData.xlsx',index=False)

In [17]:
#Read the saved Excel data from the drive 
pathExcel='/content/drive/MyDrive/Colab Notebooks/Saved_StockData.xlsx'
dataFromSaveddriveExcel=pd.read_excel(pathExcel)

In [4]:
type(data)

NameError: ignored

In [18]:
dataFromSaveddriveExcel.head()


stock       date    price
0  AAPL 2013-02-08  67.8542
1  AAPL 2013-02-11  68.5614
2  AAPL 2013-02-12  66.8428
3  AAPL 2013-02-13  66.7156
4  AAPL 2013-02-14  66.6556